/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 15.2 		*/
/*  Created On : 06-авг-2021 11:56:23 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Sequences for Autonumber Columns */

DROP SEQUENCE IF EXISTS gs_contract_gs_contract_id_seq
;

DROP SEQUENCE IF EXISTS gs_contract_condition_gs_contract_condition_id_seq
;

DROP SEQUENCE IF EXISTS gs_genres_gs_genre_id_seq
;

DROP SEQUENCE IF EXISTS gs_guitar_types_gs_guitar_type_id_seq
;

DROP SEQUENCE IF EXISTS gs_student_skill_level_gs_student_skill_level_id_seq
;

DROP SEQUENCE IF EXISTS gs_tutor_degree_level_gs_tutor_degree_level_id_seq
;

DROP SEQUENCE IF EXISTS gs_user_gs_user_id_seq
;

DROP SEQUENCE IF EXISTS gs_user_basic_info_gs_user_basic_info_id_seq
;

DROP SEQUENCE IF EXISTS gs_u_pi_gs_u_pi_id_seq
;

DROP SEQUENCE IF EXISTS gs_user_role_gs_user_role_id_seq
;

/* Drop Tables */

DROP TABLE IF EXISTS gs_contract CASCADE
;

DROP TABLE IF EXISTS gs_contract_condition CASCADE
;

DROP TABLE IF EXISTS gs_genres CASCADE
;

DROP TABLE IF EXISTS gs_guitar_types CASCADE
;

DROP TABLE IF EXISTS gs_student_skill_level CASCADE
;

DROP TABLE IF EXISTS gs_tutor_degree_level CASCADE
;

DROP TABLE IF EXISTS gs_user CASCADE
;

DROP TABLE IF EXISTS gs_user_basic_info CASCADE
;

DROP TABLE IF EXISTS gs_u_pi CASCADE
;

DROP TABLE IF EXISTS gs_user_role CASCADE
;

DROP TABLE IF EXISTS gs_blocked_user CASCADE
;

DROP TABLE IF EXISTS gs_bank_account CASCADE
;

DROP TABLE IF EXISTS gs_order CASCADE
;

/* Create Tables */


CREATE TABLE gs_genres
(
	gs_genre_id integer NOT NULL   DEFAULT NEXTVAL(('"gs_genres_gs_genre_id_seq"'::text)::regclass),
	genre varchar(20) NOT NULL
)
;

CREATE TABLE gs_guitar_types
(
	gs_guitar_type_id integer NOT NULL   DEFAULT NEXTVAL(('"gs_guitar_types_gs_guitar_type_id_seq"'::text)::regclass),
	guitar_type varchar(20) NOT NULL
)
;

CREATE TABLE gs_student_skill_level
(
	gs_student_skill_level_id integer NOT NULL   DEFAULT NEXTVAL(('"gs_student_skill_level_gs_student_skill_level_id_seq"'::text)::regclass),
	skill_level varchar(20) NOT NULL
)
;

CREATE TABLE gs_tutor_degree_level
(
	gs_tutor_degree_level_id integer NOT NULL   DEFAULT NEXTVAL(('"gs_tutor_degree_level_gs_tutor_degree_level_id_seq"'::text)::regclass),
	tutor_degree varchar(50) NOT NULL
)
;


CREATE TABLE gs_user_role
(
	gs_user_role_id integer NOT NULL   DEFAULT NEXTVAL(('"gs_user_role_gs_user_role_id_seq"'::text)::regclass),
	user_role varchar(20) NOT NULL
)
;

CREATE TABLE gs_u_pi
(
	gs_u_pi_id integer NOT NULL   DEFAULT NEXTVAL(('"gs_u_pi_gs_u_pi_id_seq"'::text)::regclass),
	user_role_id integer NULL,
	tutor_degree_level_id integer NULL,
	student_skill_level_id integer NULL
)
;



CREATE TABLE gs_contract
(
	gs_contract_id integer NOT NULL   DEFAULT NEXTVAL(('"gs_contract_gs_contract_id_seq"'::text)::regclass),
	contract_condition_id integer NOT NULL,
	tutor_id integer NOT NULL,
	student_id integer NOT NULL
)
;

CREATE TABLE gs_contract_condition
(
	gs_contract_condition_id integer NOT NULL   DEFAULT NEXTVAL(('"gs_contract_condition_gs_contract_condition_id_seq"'::text)::regclass),
	start_date date,
	finish_date date,
	guitar_type_id integer NOT NULL,
	genre_id integer NOT NULL,
	student_current_level_id integer NOT NULL,
	student_target_level_id integer NOT NULL
)
;
CREATE TABLE gs_user_basic_info
(
	gs_user_basic_info_id integer NOT NULL   DEFAULT NEXTVAL(('"gs_user_basic_info_gs_user_basic_info_id_seq"'::text)::regclass),
	email varchar(100) NOT NULL,
	user_password varchar(60) NOT NULL,
	nickname varchar(50) NOT NULL,
    is_active boolean default false
)
;


CREATE TABLE gs_user
(
	gs_user_id integer NOT NULL   DEFAULT NEXTVAL(('"gs_user_gs_user_id_seq"'::text)::regclass),
	gs_user_basic_info_id integer NOT NULL,
	gs_u_pi_id integer NOT NULL
)
;


CREATE TABLE gs_blocked_user
(
	gs_blocked_user_id serial NOT NULL primary key,
	email varchar(100), 
    unique (email)
)
;

CREATE TABLE gs_bank_account (
    gs_bank_account_id  serial primary key not null,
    bank_account_number varchar(22),
    email varchar (100) not null ,
    rest integer default 100000,
    unique(bank_account_number, email)
)
;

create table gs_order (

	gs_order_id serial,
	email varchar(100),
	genre_name varchar (20),
    isPaid boolean default false,
    isConfirmed boolean default false
);

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE gs_contract ADD CONSTRAINT "PK_gs_contract"
	PRIMARY KEY (gs_contract_id)
;

CREATE INDEX "IXFK_gs_contract_gs_contract_condition" ON gs_contract (contract_condition_id ASC)
;

CREATE INDEX "IXFK_gs_contract_gs_user" ON gs_contract (tutor_id ASC)
;

CREATE INDEX "IXFK_gs_contract_gs_user_02" ON gs_contract (student_id ASC)
;

ALTER TABLE gs_contract_condition ADD CONSTRAINT "PK_gs_contract_condition"
	PRIMARY KEY (gs_contract_condition_id)
;

CREATE INDEX "IXFK_gs_contract_condition_gs_genres" ON gs_contract_condition (genre_id ASC)
;

CREATE INDEX "IXFK_gs_contract_condition_gs_genres_02" ON gs_contract_condition (genre_id ASC)
;

CREATE INDEX "IXFK_gs_contract_condition_gs_genres_03" ON gs_contract_condition (genre_id ASC)
;

CREATE INDEX "IXFK_gs_contract_condition_gs_guitar_types" ON gs_contract_condition (guitar_type_id ASC)
;

CREATE INDEX "IXFK_gs_contract_condition_gs_guitar_types_02" ON gs_contract_condition (guitar_type_id ASC)
;

CREATE INDEX "IXFK_gs_contract_condition_gs_student_skill_level" ON gs_contract_condition (student_current_level_id ASC)
;

CREATE INDEX "IXFK_gs_contract_condition_gs_student_skill_level_02" ON gs_contract_condition (student_target_level_id ASC)
;

ALTER TABLE gs_genres ADD CONSTRAINT "PK_gs_genres"
	PRIMARY KEY (gs_genre_id)
;

ALTER TABLE gs_guitar_types ADD CONSTRAINT "PK_gs_guitar_types"
	PRIMARY KEY (gs_guitar_type_id)
;

ALTER TABLE gs_student_skill_level ADD CONSTRAINT "PK_gs_student_skill_level"
	PRIMARY KEY (gs_student_skill_level_id)
;

ALTER TABLE gs_tutor_degree_level ADD CONSTRAINT "PK_gs_tutor_degree_level"
	PRIMARY KEY (gs_tutor_degree_level_id)
;

ALTER TABLE gs_user ADD CONSTRAINT "PK_gs_user"
	PRIMARY KEY (gs_user_id)
;



CREATE INDEX "IXFK_gs_user_gs_user_basic_info" ON gs_user (gs_user_basic_info_id ASC)
;

CREATE INDEX "IXFK_gs_user_gs_u_pi" ON gs_user (gs_u_pi_id ASC)
;

ALTER TABLE gs_user_basic_info ADD CONSTRAINT "PK_gs_user_basic_info"
	PRIMARY KEY (gs_user_basic_info_id)
;

CREATE INDEX "IXFK_gs_user_basic_info_gs_user" ON gs_user_basic_info (gs_user_basic_info_id ASC)
;

ALTER TABLE gs_u_pi ADD CONSTRAINT "PK_gs_u_pi"
	PRIMARY KEY (gs_u_pi_id)
;

CREATE INDEX "IXFK_gs_u_pi_gs_student_skill_level" ON gs_u_pi (student_skill_level_id ASC)
;

CREATE INDEX "IXFK_gs_u_pi_gs_tutor_degree_level" ON gs_u_pi (tutor_degree_level_id ASC)
;

CREATE INDEX "IXFK_gs_u_pi_gs_user" ON gs_u_pi (gs_u_pi_id ASC)
;

CREATE INDEX "IXFK_gs_u_pi_gs_user_role" ON gs_u_pi (user_role_id ASC)
;

ALTER TABLE gs_user_role ADD CONSTRAINT "PK_gs_user_role"
	PRIMARY KEY (gs_user_role_id)
;

/* Create Foreign Key Constraints */

ALTER TABLE gs_contract ADD CONSTRAINT "FK_gs_contract_gs_contract_condition"
	FOREIGN KEY (contract_condition_id) REFERENCES gs_contract_condition (gs_contract_condition_id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE gs_contract ADD CONSTRAINT "FK_gs_contract_gs_user"
	FOREIGN KEY (tutor_id) REFERENCES gs_user (gs_user_id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE gs_contract ADD CONSTRAINT "FK_gs_contract_gs_user_02"
	FOREIGN KEY (student_id) REFERENCES gs_user (gs_user_id) ON DELETE No Action ON UPDATE No Action
;


ALTER TABLE gs_contract_condition ADD CONSTRAINT "FK_gs_contract_condition_gs_genres_03"
	FOREIGN KEY (genre_id) REFERENCES gs_genres (gs_genre_id) ON DELETE Set Null ON UPDATE No Action
;

ALTER TABLE gs_contract_condition ADD CONSTRAINT "FK_gs_contract_condition_gs_guitar_types"
	FOREIGN KEY (guitar_type_id) REFERENCES  gs_guitar_types (gs_guitar_type_id) ON DELETE Cascade ON UPDATE No Action
;


ALTER TABLE gs_contract_condition ADD CONSTRAINT "FK_gs_contract_condition_gs_student_skill_level"
	FOREIGN KEY (student_current_level_id) REFERENCES gs_student_skill_level (gs_student_skill_level_id) ON DELETE No Action ON UPDATE No Action
;



ALTER TABLE gs_user ADD CONSTRAINT "FK_gs_user_gs_user_basic_info"
	FOREIGN KEY (gs_user_basic_info_id) REFERENCES gs_user_basic_info (gs_user_basic_info_id) ON DELETE Set Null ON UPDATE No Action
;


ALTER TABLE gs_user ADD CONSTRAINT "FK_gs_u_pi_gs_user"
	FOREIGN KEY (gs_u_pi_id) REFERENCES  gs_u_pi (gs_u_pi_id) ON DELETE No Action ON UPDATE No Action
;


ALTER TABLE gs_u_pi ADD CONSTRAINT "FK_gs_u_pi_gs_student_skill_level"
	FOREIGN KEY (student_skill_level_id) REFERENCES gs_student_skill_level (gs_student_skill_level_id) ON DELETE Set Null ON UPDATE No Action
;

ALTER TABLE gs_u_pi ADD CONSTRAINT "FK_gs_u_pi_gs_tutor_degree_level"
	FOREIGN KEY (tutor_degree_level_id) REFERENCES gs_tutor_degree_level (gs_tutor_degree_level_id) ON DELETE No Action ON UPDATE No Action
;



ALTER TABLE gs_u_pi ADD CONSTRAINT "FK_gs_u_pi_gs_user_role"
	FOREIGN KEY (user_role_id) REFERENCES gs_user_role (gs_user_role_id) ON DELETE Set Null ON UPDATE No Action
;

/* Create Table Comments, Sequences for Autonumber Columns */

CREATE SEQUENCE gs_contract_gs_contract_id_seq INCREMENT 1 START 1
;

CREATE SEQUENCE gs_contract_condition_gs_contract_condition_id_seq INCREMENT 1 START 1
;

CREATE SEQUENCE gs_genres_gs_genre_id_seq INCREMENT 1 START 1
;

CREATE SEQUENCE gs_guitar_types_gs_guitar_type_id_seq INCREMENT 1 START 1
;

CREATE SEQUENCE gs_student_skill_level_gs_student_skill_level_id_seq INCREMENT 1 START 1
;

CREATE SEQUENCE gs_tutor_degree_level_gs_tutor_degree_level_id_seq INCREMENT 1 START 1
;

CREATE SEQUENCE gs_user_gs_user_id_seq INCREMENT 1 START 1
;

CREATE SEQUENCE gs_user_basic_info_gs_user_basic_info_id_seq INCREMENT 1 START 1
;

CREATE SEQUENCE gs_u_pi_gs_u_pi_id_seq INCREMENT 1 START 1
;

CREATE SEQUENCE gs_user_role_gs_user_role_id_seq INCREMENT 1 START 1
;


insert into gs_user_role (user_role) values
('none'),
('admin'),
('tutor'),
('student');

insert into gs_student_skill_level (skill_level) values
('none'),
('start'),
('elementary'),
('intermediate'),
('advanced');

insert into gs_tutor_degree_level (tutor_degree) values
('none'),
('junior'),
('middle'),
('senior');

insert into gs_guitar_types (guitar_type) values
('classical'),
('western'),
('electric'),
('bass'),
('slide'),
('ethno');

insert into gs_genres (genre) values
('basic'),
('metal'),
('rock'),
('blues'),
('jazz'),
('funk'),
('ethnical'),
('flamenco'),
('pop'),
('classic');


with basic_info_insert as (
		insert into gs_user_basic_info (email, user_password, nickname, is_active)
		values ('ant-2005@gmail.com', '524fab9770198b17667f350a6bb2db3201de8db7', 'Anton', 'true')
		returning gs_user_basic_info_id as b_id
),

professional_info_insert as (
	insert into gs_u_pi (user_role_id, tutor_degree_level_id, student_skill_level_id)
	values (2, 1, 1)
	returning gs_u_pi_id as p_id
)

insert into gs_user (gs_user_basic_info_id, gs_u_pi_id)
values (
(select b_id from basic_info_insert), (select p_id from professional_info_insert)
);


with basic_info_insert as (
		insert into gs_user_basic_info (email, user_password, nickname, is_active)
		values ('guitarschool.epam.user1@gmail.com', '524fab9770198b17667f350a6bb2db3201de8db7', 'user1', 'false')
		returning gs_user_basic_info_id as b_id
),

professional_info_insert as (
	insert into gs_u_pi (user_role_id, tutor_degree_level_id, student_skill_level_id)
	values (4, 1, 1)
	returning gs_u_pi_id as p_id
)

insert into gs_user (gs_user_basic_info_id, gs_u_pi_id)
values (
(select b_id from basic_info_insert), (select p_id from professional_info_insert)
);

with basic_info_insert as (
		insert into gs_user_basic_info (email, user_password, nickname, is_active)
		values ('guitarschool.epam.user2@gmail.com', '524fab9770198b17667f350a6bb2db3201de8db7', 'user2', 'true')
		returning gs_user_basic_info_id as b_id
),

professional_info_insert as (
	insert into gs_u_pi (user_role_id, tutor_degree_level_id, student_skill_level_id)
	values (4, 1, 1)
	returning gs_u_pi_id as p_id
)

insert into gs_user (gs_user_basic_info_id, gs_u_pi_id)
values (
(select b_id from basic_info_insert), (select p_id from professional_info_insert)
);

with basic_info_insert as (
		insert into gs_user_basic_info (email, user_password, nickname, is_active)
		values ('guitarschool.epam.user3@gmail.com', '524fab9770198b17667f350a6bb2db3201de8db7', 'user3', 'false')
		returning gs_user_basic_info_id as b_id
),

professional_info_insert as (
	insert into gs_u_pi (user_role_id, tutor_degree_level_id, student_skill_level_id)
	values (4, 1, 1)
	returning gs_u_pi_id as p_id
)

insert into gs_user (gs_user_basic_info_id, gs_u_pi_id)
values (
(select b_id from basic_info_insert), (select p_id from professional_info_insert)
);

with basic_info_insert as (
		insert into gs_user_basic_info (email, user_password, nickname, is_active)
		values ('guitarschool.epam.user4@gmail.com', '524fab9770198b17667f350a6bb2db3201de8db7', 'user4', 'true')
		returning gs_user_basic_info_id as b_id
),

professional_info_insert as (
	insert into gs_u_pi (user_role_id, tutor_degree_level_id, student_skill_level_id)
	values (4, 1, 1)
	returning gs_u_pi_id as p_id
)

insert into gs_user (gs_user_basic_info_id, gs_u_pi_id)
values (
(select b_id from basic_info_insert), (select p_id from professional_info_insert)
);

with basic_info_insert as (
		insert into gs_user_basic_info (email, user_password, nickname, is_active)
		values ('guitarschool.epam.user5@gmail.com', '524fab9770198b17667f350a6bb2db3201de8db7', 'user5', 'false')
		returning gs_user_basic_info_id as b_id
),

professional_info_insert as (
	insert into gs_u_pi (user_role_id, tutor_degree_level_id, student_skill_level_id)
	values (4, 1, 1)
	returning gs_u_pi_id as p_id
)

insert into gs_user (gs_user_basic_info_id, gs_u_pi_id)
values (
(select b_id from basic_info_insert), (select p_id from professional_info_insert)
);

with basic_info_insert as (
		insert into gs_user_basic_info (email, user_password, nickname, is_active)
		values ('guitarschool.epam.user6@gmail.com', '524fab9770198b17667f350a6bb2db3201de8db7', 'user6', 'true')
		returning gs_user_basic_info_id as b_id
),

professional_info_insert as (
	insert into gs_u_pi (user_role_id, tutor_degree_level_id, student_skill_level_id)
	values (4, 1, 1)
	returning gs_u_pi_id as p_id
)

insert into gs_user (gs_user_basic_info_id, gs_u_pi_id)
values (
(select b_id from basic_info_insert), (select p_id from professional_info_insert)
);

with basic_info_insert as (
		insert into gs_user_basic_info (email, user_password, nickname, is_active)
		values ('guitarschool.epam.tutor1@gmail.com', '524fab9770198b17667f350a6bb2db3201de8db7', 'tutor1', 'true')
		returning gs_user_basic_info_id as b_id
),

professional_info_insert as (
	insert into gs_u_pi (user_role_id, tutor_degree_level_id, student_skill_level_id)
	values (3, 1, 1)
	returning gs_u_pi_id as p_id
)

insert into gs_user (gs_user_basic_info_id, gs_u_pi_id)
values (
(select b_id from basic_info_insert), (select p_id from professional_info_insert)
);

with basic_info_insert as (
		insert into gs_user_basic_info (email, user_password, nickname, is_active)
		values ('guitarschool.epam.tutor2@gmail.com', '524fab9770198b17667f350a6bb2db3201de8db7', 'tutor2', 'true')
		returning gs_user_basic_info_id as b_id
),

professional_info_insert as (
	insert into gs_u_pi (user_role_id, tutor_degree_level_id, student_skill_level_id)
	values (3, 1, 1)
	returning gs_u_pi_id as p_id
)

insert into gs_user (gs_user_basic_info_id, gs_u_pi_id)
values (
(select b_id from basic_info_insert), (select p_id from professional_info_insert)
);

with basic_info_insert as (
		insert into gs_user_basic_info (email, user_password, nickname, is_active)
		values ('guitarschool.epam.tutor3@gmail.com', '524fab9770198b17667f350a6bb2db3201de8db7', 'tutor3', 'true')
		returning gs_user_basic_info_id as b_id
),

professional_info_insert as (
	insert into gs_u_pi (user_role_id, tutor_degree_level_id, student_skill_level_id)
	values (3, 1, 1)
	returning gs_u_pi_id as p_id
)

insert into gs_user (gs_user_basic_info_id, gs_u_pi_id)
values (
(select b_id from basic_info_insert), (select p_id from professional_info_insert)
);

insert into gs_bank_account (bank_account_number, email) values 
('1111-1111-1111-1111', 'guitarschool.epam.user1@gmail.com');

insert into gs_bank_account (bank_account_number, email) values 
('2222-2222-2222-2222', 'guitarschool.epam.user2@gmail.com');

insert into gs_bank_account (bank_account_number, email) values 
('3333-3333-3333-3333', 'guitarschool.epam.user3@gmail.com');


insert into gs_bank_account (bank_account_number, email) values 
('4444-4444-4444-4444', 'guitarschool.epam.user4@gmail.com');


insert into gs_bank_account (bank_account_number, email) values 
('5555-5555-5555-5555', 'guitarschool.epam.user5@gmail.com');


insert into gs_bank_account (bank_account_number, email) values 
('6666-6666-6666-6666', 'guitarschool.epam.user6@gmail.com');


